### ISSUE TITLE
Script fails on Nexus Player Kodi

### ISSUE THREAD

**Issue by MrBroox** [bromix/plugin.video.vimeo#29]
Does not even start. Version 4.1.4 on Kodi 14.2 on Nexus Player

**Comment by bromix** [comment]
Do have a debug log for me after the error.

**Comment by MrBroox** [comment]
I wonder if you did something but now it started working

**Comment by bromix** [comment]
I have special powers, which work only over the internet ;)

No, I didn't change anything :) maybe a little connection problem. Keep a eye on it, if the problem reoccurs, re-open an issue :)
